prowork/prowork/apps/agents/urls.py
from django.urls import path

from . import views

app_name = 'agents'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:city_url>/', views.index_city, name='city_url'),
    path('<str:city_url>/<str:pro>/', views.pro, name='pro'),
]

prowork/prowork/apps/general/urls.py
from django.urls import path

from . import views

app_name = 'general'
urlpatterns = [
    path('', views.first_page, name='first_page'),
    path('<str:city_url>/', views.general_city, name='city_url'),
]

prowork/prowork/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('agents/', include('agents.urls')),
    path('', include('general.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prowork/prowork/apps/agents/models.py
from django.db import models


class Agent(models.Model):
    name = models.CharField('ФИО', max_length=100)
    phone = models.CharField('Телефон', max_length=20)
    email = models.EmailField('Email')
    city = models.CharField('Город', max_length=50)
    profession = models.CharField('Профессия', max_length=50)
    # profession_description = models.CharField('Мини описание услуг', max_length=200, default='Описание услуг')
    services = models.TextField('Услуги (цена);')
    priority = models.IntegerField('Приоритет показа на странице')
    avatar = models.ImageField(upload_to='avatars', max_length=255, null=True, blank=True)

    class Meta:
        verbose_name = 'Работник'
        verbose_name_plural = 'Работники'

    def __str__(self):
        return str(self.priority) + ' ' + str(self.name)

prowork/prowork/apps/general/models.py
from django.db import models

# Create your models here.

prowork/prowork/apps/agents/views.py
from django.shortcuts import render
from .models import Agent
from django.http import HttpResponseRedirect # , Http404
# from django.urls import reverse


def index_city(request, city_url):
    workers_list = Agent.objects.filter(city=city_url).order_by('priority')
    for worker in workers_list:
        worker.serv = worker.services.split('\n')
    city_list = {elem.city for elem in Agent.objects.all()}
    city_list = sorted(city_list)
    if city_url not in city_list:
        city_url = 'Выбрать город'
    persons = [elem for elem in Agent.objects.filter(city=city_url)]
    # tmp_city = []
    # for i in persons:
    #     if i.city not in tmp_city:
    #         tmp_city.append(i.city)
    
    professions = []
    for i in persons:
        if i.profession not in professions:
            professions.append(i.profession)
        else:
            persons.remove(i)
                        
    return render(request, 'agents/index.html', {
        'workers_list': workers_list,
        'city': city_url,
        'city_list': city_list,
        'persons': persons,
    })


def pro(request, city_url, pro):
    workers_list = Agent.objects.filter(city=city_url).filter(profession=pro).order_by('priority')
    for worker in workers_list:
        worker.serv = worker.services.split('\n')
    city_list = {elem.city for elem in Agent.objects.all()}
    city_list = sorted(city_list)
    if city_url not in city_list:
        city_url = 'Выбрать город'
    persons = [elem for elem in Agent.objects.filter(city=city_url)]
    # tmp_city = []
    # for person in persons:
    #     if person.city not in tmp_city:
    #         tmp_city.append(person.city)
    
    professions = []
    for i in persons:
        if i.profession not in professions:
            professions.append(i.profession)
        else:
            persons.remove(i)
            
    
    return render(request, 'agents/index.html', {
        'workers_list': workers_list,
        'city': city_url,
        'city_list': city_list,
        'persons': persons,
    })


def index(request):
    return HttpResponseRedirect('Курск')

prowork/prowork/apps/general/views.py
from django.shortcuts import render
from agents.models import Agent
from django.http import HttpResponseRedirect


def general_city(request, city_url):
    city_list = {elem.city for elem in Agent.objects.all()}
    city_list = sorted(city_list)
    persons = [elem for elem in Agent.objects.filter(city=city_url)]
    # tmp_city = []
    # for i in persons:
    #     if i.city not in tmp_city:
    #         tmp_city.append(i.city)
    
    professions = []
    for i in persons:
        if i.profession not in professions:
            professions.append(i.profession)
        else:
            persons.remove(i)

    if city_url not in city_list:
        city_url = 'Ваш Город'
    return render(request, 'general/index.html', {
        'city': city_url,
        'city_list': city_list,
        'persons': persons,
    })


def first_page(request):
    return HttpResponseRedirect('Курск')

prowork/prowork/templates/agents/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Agents{% endblock %}
{% block stat %}
  <link rel="stylesheet" href="{% static 'css/agents_style.css' %}">
  <script src="{% static 'js/agents_script.js' %}"></script>
{% endblock %}

{% block general %}

<div class="m-menu-wrapper">
  <header class="m-header">
    <div class="m-container">
      <div class="m-header-body">
        <a href="{% url "general:city_url" city_url=city %}" class="m-header-logo">
          <img src="{% static 'img/logo.jpg' %}" alt="">
        </a>
        <div class="m-header-burger">
          <span></span>
        </div>
        <nav class="m-header-menu">
          <ul class="m-header-list">
            <li>
              <a href="{% url "general:city_url" city_url=city %}" class="m-header-link gen_menu">На главную</a>
            </li>
            <li>
              <a href="#anch-masters" class="m-header-link gen_menu">Мастера</a>
            </li>
            <li>
              <a href="#anch-uslugi" class="m-header-link gen_menu">Услуги</a>
            </li>
            <li>
              <a href="#anch-contacts" class="m-header-link gen_menu">Контакты</a>
            </li>
            <li>
              <a id="myBtn" href="#" class="m-header-link m-button">
                {{ city }}
              </a>

              <div id="myModal" class="modal">
              <div class="modal-content">
                <span class="close">&times;</span>
                <h2>Выбрать город:</h2>
                <div class="check">
                <ul class="city-list">

                  {% for elem in city_list %}
                    <a href="/agents/{{ elem }}"><li class="city-item">{{ elem }}</li></a>
                  {% endfor %}

                </ul>
              </div>
              </div>
            </div>

            </li>
          </ul>
        </nav>
      </div>
    </div>
  </header>
  </div>

    <main>
      <section id="anch-masters" class="agents">
        <div class="wrapper">
          <h2>Знакомьтесь с нашими мастерами!</h2>
          <p>Как получить услуга?</p>
          <p>
            Внимательно ознакомьтесь с перечнем основных услуг мастера.<br />
            После этого <a href="#anch-contacts" class="m-link">позвоните</a> нам или 
            <a href="#anch-contacts" class="m-link">напишите</a> на нашу почту.
          </p>

          <div class="agent-cards">

            {% if workers_list %}
              {% for worker in workers_list %}

            <div class="agent-desc">
              <div class="agent-card">
                    <img src={{ worker.avatar.url }} alt="">
                <div class="agent-info">
                  <div class="name-email">
                    <p class="agent-name">{{ worker.name }}</p>
                    <p class="agent-profession">{{ worker.profession }}</p>
                  </div>
                  <div class="agent-block">
                    <p class="phone">{{ worker.phone }}</p>
                  </div>
                  <div class="agent-block2">
                    <p class="email">{{ worker.email }}</p>
                  </div>
                </div>
              </div>
              <div class="description">
                <h2 class="agent-uslugi">Предоставляемые услуги:</h2>
                <ul class="uslugi-list">

                  {% for s in worker.serv %}
                  <li><a class="uslugi-link" href="#anch-contacts">{{ s }}</a></li>
                  {% endfor %}

                </ul>
              </div>
            </div>
              {% endfor %}
            {% else %}
              <h2>В настоящее время в вашем городе мы не работаем</h2>
            {% endif %}
          </div>
        </div>
      </section>
{% endblock %}

      <section class="apartmens">
        <div class="u-wrapper uslugi">
          <h2 id="anch-uslugi">
            Lorem, ipsum dolor.
          </h2>
          <p class="par">Lorem ipsum dolor sit, amet consectetur adipisicing.</p>
          <ul class="cards">

            {% if persons %}

            {% for prof in persons %}
              <li class="h-list">
                <div class="descr">
                  <h3 class="headline">{{ prof.profession }}</h3>
                  <p>{{ prof.profession_description }}</p>
                  <div class="h-link">
                    <a href="/agents/{{ city }}/{{ prof.profession }}" class="h-button">К нашим мастерам</a>
                  </div>
                </div>
                <img class="u-img" src="/static/img/{{ prof.profession }}.jpg" alt="Alt" />
              </li>
            {% endfor %}

            {% else %}
            <p>На данный момент мы не работаем в Вашем городе</p>

            {% endif %}

          </ul>
        </div>
      </section>
  

prowork/prowork/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Мой сайт{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="{% static 'js/base.js' %}"></script>
    {% block stat %}{% endblock %}
  </head>
<body>

    {% block general %}{% endblock %}

    {% block choose_master %}
      <section class="apartmens">
        <div class="u-wrapper uslugi">
          <h2 id="anch-uslugi">
            Наши услуги
          </h2>
          <p class="par">Выберите необходимого специалиста</p>
          <ul class="cards">

            {% if persons %}

            {% for prof in persons %}
              <li class="h-list">
                <div class="descr">
                  <h3 class="headline">{{ prof.profession }}</h3>
                  {% comment %} <p>{{ prof.profession_description }}</p> {% endcomment %}
                  <div class="h-link">
                    <a href="/agents/{{ city }}/{{ prof.profession }}" class="h-button">К нашим мастерам</a>
                  </div>
                </div>
                <img class="u-img" src="/static/img/{{ prof.profession }}.jpg" alt="Alt" />
              </li>
            {% endfor %}

            {% else %}
            <p>На данный момент мы не работаем в Вашем городе</p>

            {% endif %}

          </ul>
        </div>
      </section>
    {% endblock %}

    {% block reviews %}{% endblock %}

    {% block contacts %}
      <section id="anch-contacts" class="contacts">
          <div class="wrap">
            <div class="contacts_form wrapper">
              <h3>Свяжитесь с нами:</h3>
              <p class="phone">
                <span class="jir">Phone: </span>+7 961 168 60 04
              </p>
              <p class="email">
                <span class="jir">Email: </span>prowork_kursk@mail.ru
              </p>
            </div>
          </div>
        </section>
    {% endblock %}

    {% block footer %}
      <footer>
      <div class="wrapper">
        <div class="footer-block">
          <div class="footer-logo">
            <h3>Prowork</h3>
            <h3>Твой личный мастер</h3>
          </div>
          <div class="footer-text">
            <p>
              Сайт не является публичной офертой и носит информационный 
              характер.<br />             
            </p>
            <p class="sobaka">
              ©All rights reserved
            </p>
          </div>
        </div>
      </div>
    </footer>
    {% endblock %}
</body>
</html>

prowork/prowork/templates/general/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Prowork{% endblock %}
{% block stat %}
<link rel="stylesheet" href="{% static 'css/general_style.css' %}">
<script
      src="https://kit.fontawesome.com/6244ce2d4b.js"
      crossorigin="anonymous">
</script>
<script src="{% static 'js/general_script.js' %}"></script>
{% endblock %}

{% block general %}


<div class="m-menu-wrapper">
  <header class="m-header">
    <div class="m-container">
      <div class="m-header-body">
        <a href="{% url "general:city_url" city_url=city %}" class="m-header-logo">
          <img src="{% static 'img/logo.jpg' %}" alt="">
        </a>
        <div class="m-header-burger">
          <span></span>
        </div>
        <nav class="m-header-menu">
          <ul class="m-header-list">
            <li>
              <a href="#anch-start" class="m-header-link gen_menu">К началу</a>
            </li>
            <li>
              <a href="#anch-about" class="m-header-link gen_menu">О нас</a>
            </li>
            <li>
              <a href="#anch-uslugi" class="m-header-link gen_menu">Услуги</a>
            </li>
            <li>
              <a href="#anch-feedback" class="m-header-link gen_menu">Отзывы</a>
            </li>
            <li>
              <a href="#anch-contacts" class="m-header-link gen_menu">Контакты</a>
            </li>
            <li>
              <a id="myBtn" href="#" class="m-header-link m-button">{{ city }}</a>

             <div id="myModal" class="modal">
              <div class="modal-content">
                <span class="close">&times;</span>
                <h2>Выбрать город:</h2>
                <div class="check">
                <ul class="city-list">

                  {% for elem in city_list %}
                    <a href="/{{ elem }}"><li class="city-item">{{ elem }}</li></a>
                  {% endfor %}

                </ul>
              </div>
              </div>
            </div>

            </li>
          </ul>
        </nav>
      </div>
    </div>
  </header>
  </div>


    <main>
      <section class="intro wrapper" id="anch-start">
        <div class="intro-img">
          <p class="intro-text">
            Prowork-твой<br />
            личный мастер!
          </p>
        </div>
        <div class="intro-contacts">
          <p><i class="fas fa-phone-alt"></i>(961)1686-004</p>
          <p><i class="fas fa-map-marker-alt"></i> <a id="second_btn" href="#">{{ city }}</a> </p>
        </div>
      </section>


      <section class="services wrapper2">
        <div class="wrapper">
        <h2 id="anch-about">О нас</h2>
        <p class="serv-desc">Сломался унитаз или течёт раковина?</p>
        <p class="serv-desc">Нужно провести розетки, а Вы не знаете как?</p>
        <p class="serv-desc">Prowork поможет!</p>
        <p class="serv-desc">Широкий спектор услуг: от сантехнических работ до электрики и работы спецтехники!</p>
        <p class="serv-desc">Почему Prowork?</p>
        <div class="serv-container">
          <div class="serv-img-container">
            <img src="{% static 'img/servroom.jpg' %}" alt="" />
          </div>
          <div class="serv-text">
            <h4>Высокое качество</h4>
            <p>
              Мы очень трепетно относимся к выполнению любых видов работ! 
              Поэтому достойное качество определённо является одной из сильных сторон Prowork. 
              Не сомневайтесь, Вы будете довольными! 
            </p>
            <h4>Квалифицированные специалисты</h4>
            <p>
              В Prowork работают только высококвалифицированные специалисты, 
              хорошо знающие своё дело. Кроме того, у работников имеются разрешение 
              на работу со специализированной техникой. 
            </p>
            <h4>Доступная цена</h4>
            <p>
              Демократические цены, а также действующие скидки и акции без труда позволят выбрать необходимую Вам услугу!
            </p>
          </div>
        </div>
      </div>
      </section>

  {% endblock %}

  {% block reviews %}

        <section class="c-header">
          <h2 id="anch-feedback" class="c-header2">Наши клиенты любят нас</h2>
          <ul class="c-cards">

            <li>
              <div class="c-container">
                <div class="c-header-body">
                  <a href="#" class="c-header-logo">
                    <img src="{% static 'img/avatar_man.jpg' %}" alt="">
                  </a>
                  <div class="media-body">
                    <h4 class="media-heading">Михаил Р.</h4>
                    <span>18.01.2020 </span>
                  </div>
                </div>
                <div class="feedback-text">
                  <p>
                    Ребята хорошие и веселые, но разобраться до конца не смогли...
                    Оплату, к удивлению, за не выполненную работу не взяли!
                    Обещали обдумать ситуацию и заехать ещё. Ждём)
                  </p>
                </div>
              </div>
            </li>

            <li>
              <div class="c-container">
                <div class="c-header-body">
                  <a href="#" class="c-header-logo">
                    <img src="{% static 'img/avatar_girl.png' %}" alt="">
                  </a>
                  <div class="media-body">
                    <h4 class="media-heading">Марина Ж.</h4>
                    <span>26.01.2020</span>
                  </div>
                </div>
                <div class="feedback-text">
                  <p>
                  1) Добросовестная работа сотрудников компании. 
                  2) Хорошие цены на услуги. 
                  3) после того как позвонила, приехал мастер. 
                  4) Вызывала для установки электрики. За пару часов всё выполнил.
                </p>
                </div>
              </div>
            </li>

            <li>
              <div class="c-container">
                <div class="c-header-body">
                  <a href="#" class="c-header-logo">
                    <img src="{% static 'img/avatar_girl.png' %}" alt="">
                  </a>
                  <div class="media-body">
                    <h4 class="media-heading">Наталья С.</h4>
                    <span>20.02.2020</span>
                  </div>
                </div>
                <div class="feedback-text">
                  <p>
                    Срочно нужен был электрик. Позвонила - приехал в течение 15 минут, всё сделал. Осталась довольна!  
                  </p>
                </div>
              </div>
            </li>

            <li>
              <div class="c-container">
                <div class="c-header-body">
                  <a href="#" class="c-header-logo">
                    <img src="{% static 'img/avatar_man.jpg' %}" alt="">
                  </a>
                  <div class="media-body">
                    <h4 class="media-heading">Устин Л.</h4>
                    <span>06.02.2020</span>
                  </div>
                </div>
                <div class="feedback-text">
                  <p>
                    Отличная команда,сделали весь объем за один день,сэкономили много времени!
                    спасибо! 
                  </p>
                </div>
              </div>
            </li>

          </ul>
        </section>

    {% endblock %}
    
    </main>